JWT 기반 게임회사 관련 로그인 및 회원가입 로직들과 게임 추가 기능들을 구현
gameProb/gameVal_backend pull request #1
Opened 2024-08-04 13:20 UTC by haebyun

2024-08-04 16:44 UTC, seate commented on src/main/java/com/project/gameVal/common/Exception/CommonExceptionHandler.java
> +package com.project.gameVal.common.Exception;
패키지 앞글자 대문자로 하셨어요

2024-08-04 19:14 UTC, seate requested changes
리뷰한 거 확인하시고 다시 얘기해요

2024-08-04 19:14 UTC, seate commented on src/main/java/com/project/gameVal/common/Exception/CommonExceptionHandler.java
> +package com.project.gameVal.common.Exception;
패키지 첫글자 대문자로 하셨어요

2024-08-04 19:14 UTC, seate commented on src/main/java/com/project/gameVal/common/JWT/Repository/LogoutRedisRepository.java
> +    <S extends LogoutAccessToken> S save(@NonNull S entity);
data jpa에서 제공하는 메서드를 override한 이유가 있나요?
@NonNull때문인가요?

2024-08-04 19:14 UTC, seate commented on src/main/java/com/project/gameVal/common/JWT/auth/JWTUtil.java
> +        byte[] keyBytes = Base64.getDecoder().decode(accessTokenSecretKey);
key를 encode해서 갖고 있다가 decode해서 사용하는 이유가 있나요?

2024-08-04 19:14 UTC, seate commented on src/main/java/com/project/gameVal/common/JWT/auth/JWTAuthenticationFilter.java
> +        refreshCookie.setPath("/");  // 모든 경로에서 접근 가능하도록 설정
refreshToken을 사용하는 이유가 accessToken의 탈취를 대비하여 access Token의 주기를 짧게 하기 위해 사용하는 건데 모든 경로에서 사용가능하게 하면 refreshToken을 사용하는 이유가 퇴색될 것 같아요.
 그래서 reIssue 부분에서만 사용하게 해야 할 것 같아요

2024-08-04 19:14 UTC, seate commented on src/main/java/com/project/gameVal/common/config/SecurityConfig.java
> +                .addFilterBefore(
UsernamePasswordAuthenticationFilter를 jwtAuthenticationFilter로 대체하는 거니까 addFilterBefore 대신에 addFilterAt을 사용해야 할 것 같아요

2024-08-04 19:14 UTC, seate commented on src/main/java/com/project/gameVal/common/JWT/auth/JWTAuthorizationFilter.java
> +            if (!logoutAccessTokenService.isValid(accessToken)) {
제가 생각해봤는데 authorization 시에 db 조회가 필요 없도록 변경할 필요가 있을 것 같아요
이건 일단 merge하고 제가 해결할게요

2024-08-05 01:18 UTC, haebyun commented on src/main/java/com/project/gameVal/common/JWT/auth/JWTUtil.java
> +        byte[] keyBytes = Base64.getDecoder().decode(accessTokenSecretKey);
만약, 비밀 키를 외부에 저장하여 이를 사용하는 경우에는 인코딩을 하여 저장하는 등의 작업이 보안의 관점에서 좋지만, 현재의 상황은 프로젝트 내부에서만 비밀키를 사용하고 있기 때문에 이러한 로직이 필요가 없어보입니다.
그렇기에 수정하겠습니다!

2024-08-05 01:35 UTC, haebyun commented on src/main/java/com/project/gameVal/common/JWT/auth/JWTAuthenticationFilter.java
> +        refreshCookie.setPath("/");  // 모든 경로에서 접근 가능하도록 설정
좋은 지적이라고 생각합니다!
수정하겠습니다

2024-08-05 01:36 UTC, haebyun commented on src/main/java/com/project/gameVal/common/Exception/CommonExceptionHandler.java
> +package com.project.gameVal.common.Exception;
수정하겠습니다

2024-08-05 01:40 UTC, haebyun commented on src/main/java/com/project/gameVal/common/config/SecurityConfig.java
> +                .addFilterBefore(
수정하겠습니다!

2024-08-05 01:42 UTC, haebyun commented on src/main/java/com/project/gameVal/common/JWT/Repository/LogoutRedisRepository.java
> +    <S extends LogoutAccessToken> S save(@NonNull S entity);
이것은 CrudRepository 인터페이스(부모 인터페이스)에서 정의된 메서드를 재정의 하고 있다는 것을 명확하게 표현할 수 있다는 장점이 있지만, 코드의 통일성 관점에서는 지우는 것이 나을 것 같습니다.
수정하겠습니다!

2024-08-05 02:03 UTC, haebyun commented on src/main/java/com/project/gameVal/common/JWT/Repository/LogoutRedisRepository.java
> +    <S extends LogoutAccessToken> S save(@NonNull S entity);
넵! @NonNull을 사용하여 null을 허용하지 않는다는 것을 명확하게 표현하는 것이 더 좋을 것 같다고 생각합니다.
그런데 이렇게 생각해보았을 때, 다른 repository 클래스 들에도 @NonNull을 넣어주어서 통일성을 부여함과 동시에 조금 더 안전한 코드가 될 수 있을 것 같습니다.
다른 repository의 메서드들에도 @NonNull을 추가할까 하는데 어떻게 생각하시나요?

2024-08-05 13:09 UTC, seate commented on src/main/java/com/project/gameVal/common/JWT/Repository/LogoutRedisRepository.java
> +    <S extends LogoutAccessToken> S save(@NonNull S entity);
말씀하신 방법의 주요 장단점은

장점: 조금 더 안전한 코드
단점: 작성해야 할 코드 증가

등이 있을 것 같습니다. 사실 지금 작성된 repository 메서드들을 보면 null을 넣을만한 메서드가 있는 것 같진 않은데, 
추후 안전성을 위해 @NonNull을 작성해도 괜찮을 것 같습니다.

2024-08-05 13:28 UTC, merged